name: coldstore
description: A Firestore caching layer for offline persistence
version: 0.1.0
repository: https://github.com/alistair-riskmemo/coldstore
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
