name: coldstore
description: A Firestore caching layer for offline persistence
version: 0.1.0
# repository: https://github.com/yourusername/coldstore

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  build_runner: ^2.4.15
